# SonarQube Cloud project configuration
sonar.projectKey=damir1240111_Bye-Bye-Johns
sonar.organization=damir1240111
sonar.projectName=Bye-Bye Johns

# Paths to source directories
sonar.sources=src,src-tauri/src
sonar.tests=

# Language-specific settings
sonar.javascript.tsconfigPath=tsconfig.json

# Exclusions (exclude build files, node modules, and binary target paths)
sonar.exclusions=node_modules/**,src-tauri/target/**,dist/**,public/**
