name: "Snyk Dependency Security Scan"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual trigger from the GitHub Actions UI

jobs:
  snyk-scan:
    name: Snyk Dependency Check
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20

      # Scan frontend npm dependencies
      - name: Run Snyk to check npm dependencies
        uses: snyk/actions/node@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
        continue-on-error: true # Ensure we proceed to upload the results
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-npm.sarif

      # Scan backend rust cargo dependencies
      - name: Run Snyk to check Rust cargo dependencies
        uses: snyk/actions/rust@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
        continue-on-error: true # Ensure we proceed to upload the results
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-rust.sarif

      # Upload results to GitHub Code Scanning
      - name: Upload Snyk NPM results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-npm.sarif
          category: snyk-npm

      - name: Upload Snyk Rust results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-rust.sarif
          category: snyk-rust
